--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Blugin/IgnoreCase-PMMP/IgnoreCase
build-by-default: true
branches:
- master
projects:
  IgnoreCase:
    path: ""
    icon: "icon.png"
...
