---
name: IgnoreCase
main: kim\present\ignorecase\IgnoreCase
version: 1.0.1
api: [3.0.0, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/IgnoreCase-PMMP
description: Ignore case when use the command!
...