---
name: IgnoreCase
main: kim\present\ignorecase\IndividualChest
version: 0.0.1-DEV
api: [3.0.0, 4.0.0]
author: PresentKim
website: https://github.com/PresentKim/IgnoreCase-PMMP
description: Ignore case when use the command!
...